// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAclkKEMjBb2dQLYpg4OtYyM1a18OGUqUY',
    appId: '1:599759290685:web:50af32804d77a05fbbc554',
    messagingSenderId: '599759290685',
    projectId: 'esp32-e0a40',
    authDomain: 'esp32-e0a40.firebaseapp.com',
    databaseURL: 'https://esp32-e0a40-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-e0a40.appspot.com',
    measurementId: 'G-KXLY7NE6GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAclkKEMjBb2dQLYpg4OtYyM1a18OGUqUY',
    appId: '1:599759290685:android:50af32804d77a05fbbc554',
    messagingSenderId: '599759290685',
    projectId: 'esp32-e0a40',
    databaseURL: 'https://esp32-e0a40-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-e0a40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAclkKEMjBb2dQLYpg4OtYyM1a18OGUqUY',
    appId: '1:599759290685:ios:50af32804d77a05fbbc554',
    messagingSenderId: '599759290685',
    projectId: 'esp32-e0a40',
    databaseURL: 'https://esp32-e0a40-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-e0a40.appspot.com',
    iosBundleId: 'com.example.demo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAclkKEMjBb2dQLYpg4OtYyM1a18OGUqUY',
    appId: '1:599759290685:ios:50af32804d77a05fbbc554',
    messagingSenderId: '599759290685',
    projectId: 'esp32-e0a40',
    databaseURL: 'https://esp32-e0a40-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-e0a40.appspot.com',
    iosBundleId: 'com.example.demo1',
  );
}
